import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Gelo',
      email: 'angelo@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Gab',
      email: 'gab@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Chef's Knife",
      slug: 'chef-knife',
      category: 'knife',
      image: '/images/chef-knife.jpg',
      price: 49.99,
      countInStock: 250,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        "Looking for the perfect knife for your kitchen? Our chef's knife is a versatile and essential tool that is perfect for a wide range of tasks, including chopping, dicing, mincing, and slicing. Made from high-quality stainless steel or carbon steel, our chef's knife is durable and sharp, making it the perfect addition to your kitchen toolkit.",
    },
    {
      name: 'Paring Knife',
      slug: 'paring-knife',
      category: 'knife',
      image: '/images/paring-knife.jpg',
      price: 39.99,
      countInStock: 200,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        'Introducing the Paring Knife - the perfect tool for precise and delicate cutting tasks. With its sharp, pointed blade, our Paring Knife is ideal for peeling and trimming fruits and vegetables, as well as for intricate garnishes and decorations. Compact and lightweight, this knife is a must-have for any home cook or professional chef.',
    },
    {
      name: 'Boning Knife',
      slug: 'boning-knife',
      category: 'knife',
      image: '/images/boning-knife.jpg',
      price: 79.99,
      countInStock: 200,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        "Effortlessly separate meat from bone with our Boning Knife. With its thin and flexible blade, this knife is perfect for removing bones from poultry, fish, and meats, as well as for filleting and trimming. Whether you're a professional chef or a home cook, our Boning Knife is an essential tool for your kitchen.",
    },
    {
      name: 'Bread Knife',
      slug: 'bread-knife',
      category: 'knife',
      image: '/images/bread-knife.jpg',
      price: 29.99,
      countInStock: 100,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        "Get perfectly sliced bread every time with our Bread Knife. With its serrated edge and long, thin blade, this knife is perfect for slicing through loaves of bread without crushing or tearing the soft interior. Whether you're slicing artisanal loaves or sandwich bread, our Bread Knife is a must-have for any home cook or professional chef.",
    },
    {
      name: 'Smart Oven Air Fryer Pro',
      slug: 'smart-oven-air-fryer-pro',
      category: 'appliance',
      image: '/images/smart-oven.png',
      price: 249.99,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        'Introducing the Smart Oven Air Fryer Pro - the ultimate kitchen appliance for healthy, delicious cooking. With its powerful convection oven and air fryer technology, this smart oven allows you to roast, bake, broil, and air fry your favorite foods with minimal oil. Featuring built-in Wi-Fi and a range of cooking presets, the Smart Oven Air Fryer Pro makes it easy to cook your favorite meals with precision and ease.',
    },
    {
      name: 'Food Processor',
      slug: 'food-processor',
      category: 'appliance',
      image: '/images/food-processor.png',
      price: 249.99,
      countInStock: 0,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        "Save time in the kitchen with our powerful Food Processor. With its large capacity bowl and multiple attachments, this appliance makes it easy to chop, blend, and mix a wide range of ingredients. Whether you're making dips, spreads, or dough, our Food Processor is an essential tool for any home cook or professional chef.",
    },
    {
      name: 'Explorian Blender',
      slug: 'explorian-blender',
      category: 'appliance',
      image: '/images/explorian-blender.png',
      price: 199.99,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        'Effortlessly blend, chop, and puree your favorite ingredients with our Explorian Blender. Featuring a powerful motor and a range of attachments, this appliance is perfect for making smoothies, soups, sauces, and more. With its durable design and easy-to-use controls, our Explorian Blender is a must-have for any home cook or professional chef.',
    },
    {
      name: 'Stand Mixer',
      slug: 'stand-mixer',
      category: 'appliance',
      image: '/images/stand-mixer.png',
      price: 199.99,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        'Effortlessly mix, beat, and whip your favorite ingredients with our Stand Mixer. With its powerful motor and a range of attachments, this appliance is perfect for making cakes, cookies, bread, and more. Featuring a durable design and multiple speed settings, our Stand Mixer is a must-have for any home cook or professional baker.',
    },
    {
      name: 'Measuring Cups, Set of 8',
      slug: 'measuring-cups',
      category: 'kitchen tools',
      image: '/images/measuring-cups.png',
      price: 149.99,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        "Get precise measurements every time with our Set of 8 Measuring Cups. Made from durable stainless steel, these cups come in a range of sizes, from 1/4 teaspoon to 1 cup, making it easy to measure both dry and liquid ingredients. Whether you're a home cook or a professional chef, our Measuring Cups are a must-have for any kitchen.",
    },
    {
      name: 'Bamboo Cutting Boards',
      slug: 'bamboo-cutting-boards',
      category: 'kitchen tools',
      image: '/images/bamboo-cutting-boards.png',
      price: 84.99,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        "Upgrade your kitchen with our Bamboo Cutting Boards. Made from durable and sustainable bamboo, these cutting boards are gentle on knives and provide a stable surface for all of your cutting needs. With a range of sizes and a beautiful natural finish, our Bamboo Cutting Boards are a stylish and practical addition to any home cook or professional chef's kitchen.",
    },
    {
      name: 'Silicone-Tipped Tongs, 9 Inch',
      slug: 'silicone-tipped-tongs',
      category: 'kitchen tools',
      image: '/images/silicone-tipped-tongs.png',
      price: 44.99,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        'Effortlessly flip and serve your favorite foods with our 9 Inch Silicone-Tipped Tongs. Made from durable stainless steel and featuring silicone tips, these tongs are perfect for handling hot foods without scratching your cookware. With a locking mechanism for easy storage and a range of colors to choose from, our Silicone-Tipped Tongs are a must-have for any home cook or professional chef.',
    },
    {
      name: 'Silicone Whisk',
      slug: 'silicone-whisk',
      category: 'kitchen tools',
      image: '/images/silicone-whisk.png',
      price: 54.99,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        'Effortlessly mix and whisk your favorite ingredients with our Silicone Whisk. Made from durable silicone and featuring a sturdy handle, this whisk is perfect for mixing sauces, dressings, and more. With a heat-resistant design and a range of colors to choose from, our Silicone Whisk is a must-have for any home cook or professional chef.',
    },
    {
      name: 'Steel Stockpot',
      slug: 'steel-stockpot',
      category: 'cookware',
      image: '/images/steel-stockpot.png',
      price: 249.99,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        'Upgrade your kitchen with our Steel Stockpot. Made from durable stainless steel and featuring a heavy-duty design, this stockpot is perfect for boiling, simmering, and steaming a wide range of foods. With a range of sizes to choose from and a comfortable handle, our Steel Stockpot is a must-have for any home cook or professional chef.',
    },
    {
      name: 'Double Handled Skillet',
      slug: 'double-handled-skillet',
      category: 'cookware',
      image: '/images/double-handled-skillet.png',
      price: 199.99,
      countInStock: 0,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        'Effortlessly cook and serve your favorite dishes with our Double Handled Skillet. Made from durable stainless steel and featuring a non-stick coating, this skillet is perfect for frying, sauteing, and more. With double handles for easy lifting and a range of sizes to choose from, our Double Handled Skillet is a must-have for any home cook or professional chef.',
    },
    {
      name: 'Carbon Steel Wok',
      slug: 'carbon-steel-wok',
      category: 'cookware',
      image: '/images/carbon-steel-wok.png',
      price: 249.99,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        'Effortlessly stir fry and saute your favorite dishes with our Carbon Steel Wok. Made from durable carbon steel and featuring a flat bottom, this wok is perfect for use on a range of cooking surfaces. With a comfortable handle and a range of sizes to choose from, our Carbon Steel Wok is a must-have for any home cook or professional chef.',
    },
    {
      name: 'Steel Saucepan with Lid',
      slug: 'steel-saucepan-with-lid',
      category: 'cookware',
      image: '/images/steel-saucepan-with-lid.png',
      price: 349.99,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        'Effortlessly cook and serve your favorite dishes with our Steel Saucepan with Lid. Made from durable stainless steel and featuring a non-stick coating, this saucepan is perfect for boiling, simmering, and more. With a comfortable handle and a range of sizes to choose from, our Steel Saucepan with Lid is a must-have for any home cook or professional chef.',
    },
    {
      name: 'Silicone Spatula',
      slug: 'silicone-spatula',
      category: 'bakeware',
      image: '/images/silicone-spatula.png',
      price: 49.99,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        'Effortlessly mix and scrape your favorite ingredients with our Silicone Spatula. Made from durable silicone and featuring a comfortable handle, this spatula is perfect for mixing, spreading, and flipping a wide range of foods. With a heat-resistant design and a range of colors to choose from, our Silicone Spatula is a must-have for any home cook or professional chef.',
    },
    {
      name: 'Glass Measuring Cup',
      slug: 'glass-measuring-cup',
      category: 'bakeware',
      image: '/images/glass-measuring-cup.png',
      price: 44.99,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        'Effortlessly measure and pour your favorite ingredients with our Glass Measuring Cup. Made from durable and heat-resistant glass, this measuring cup is perfect for measuring both dry and liquid ingredients. With clear markings and a range of sizes to choose from, our Glass Measuring Cup is a must-have for any home cook or professional chef.',
    },
    {
      name: 'Rustic Ceramic Bakers',
      slug: 'rustic-ceramic-bakers',
      category: 'bakeware',
      image: '/images/rustic-ceramic-bakers.png',
      price: 39.99,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        'Add a touch of rustic charm to your kitchen with our Ceramic Bakers. Made from durable and oven-safe ceramic, these bakers are perfect for baking, roasting, and serving a wide range of dishes. With a beautiful rustic finish and a range of sizes to choose from, our Ceramic Bakers are a must-have for any home cook or professional chef.',
    },
    {
      name: 'Craft Sheet Pan',
      slug: 'craft-sheet-pan',
      category: 'bakeware',
      image: '/images/craft-sheet-pan.png',
      price: 34.99,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        'Upgrade your kitchen with our Craft Sheet Pan. Made from durable and heavy-duty aluminum, this sheet pan is perfect for baking, roasting, and more. With a non-stick coating and a range of sizes to choose from, our Craft Sheet Pan is a must-have for any home cook or professional chef.',
    },
  ],
};
export default data;
