import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Gelo',
      email: 'angelo@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Gab',
      email: 'gab@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Chef's Knife",
      slug: 'chef-knife',
      category: 'knife',
      image: '/images/chef-knife.jpg',
      price: 200,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description:
        "Are you in need of a reliable and versatile knife for your kitchen? Look no further! is the ultimate tool for any home cook or professional chef. With its broad, rectangular blade and sharp point, it is perfect for a wide range of tasks, including chopping, dicing, mincing, and slicing. Whether you are preparing fruits and vegetables for a salad, or slicing meats for a meal, the chef's knife is the perfect tool for the job. Made from high-quality stainless steel or carbon steel, our chef's knives are built to last. The handle is ergonomically designed to provide a comfortable and secure grip, making it easy to handle even the toughest ingredients. With a blade length of 6 to 14 inches, you'll have plenty of room to work with. The chef's knife is perfect for all of your kitchen needs, and is a must-have for any home cook or professional chef.",
    },
    {
      name: 'Paring Knife',
      slug: 'paring-knife',
      category: 'knife',
      image: '/images/paring-knife.jpg',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Knife for Peeling and Trimming',
    },
    {
      name: 'Boning Knife',
      slug: 'boning-knife',
      category: 'knife',
      image: '/images/boning-knife.jpg',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
    {
      name: 'Bread Knife',
      slug: 'bread-knife',
      category: 'knife',
      image: '/images/bread-knife.jpg',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
    {
      name: 'Smart Oven Air Fryer Pro',
      slug: 'smart-oven-air-fryer-pro',
      category: 'appliance',
      image: '/images/smart-oven.png',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
    {
      name: 'Food Processor',
      slug: 'food-processor',
      category: 'appliance',
      image: '/images/food-processor.png',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
    {
      name: 'Explorian Blender',
      slug: 'explorian-blender',
      category: 'appliance',
      image: '/images/explorian-blender.png',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
    {
      name: 'Stand Mixer',
      slug: 'stand-mixer',
      category: 'appliance',
      image: '/images/dress.png',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
    {
      name: 'Measuring Cups, Set of 8',
      slug: 'measuring-cups',
      category: 'kitchen tools',
      image: '/images/measuring-cups.png',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
    {
      name: 'Bamboo Cutting Boards',
      slug: 'bamboo-cutting-boards',
      category: 'kitchen tools',
      image: '/images/bamboo-cutting-boards.png',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
    {
      name: 'Silicone-Tipped Tongs, 9 Inch',
      slug: 'silicone-tipped-tongs',
      category: 'kitchen tools',
      image: '/images/silicone-tipped-tongs.png',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
    {
      name: 'Silicone Whisk',
      slug: 'silicone-whisk',
      category: 'kitchen tools',
      image: '/images/silicone-whisk.png',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
    {
      name: 'Steel Stockpot',
      slug: 'steel-stockpot',
      category: 'cookware',
      image: '/images/steel-stockpot.png',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
    {
      name: 'Double Handled Skillet',
      slug: 'double-handled-skillet',
      category: 'cookware',
      image: '/images/double-handled-skillet.png',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
    {
      name: 'Carbon Steel Wok',
      slug: 'carbon-steel-wok',
      category: 'cookware',
      image: '/images/carbon-steel-wok.png',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
    {
      name: 'Steel Saucepan with Lid',
      slug: 'steel-saucepan-with-lid',
      category: 'cookware',
      image: '/images/steel-saucepan-with-lid.png',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
    {
      name: 'Silicone Spatula',
      slug: 'silicone-spatula',
      category: 'bakeware',
      image: '/images/stand-mixer.png',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
    {
      name: 'Glass Measuring Cup',
      slug: 'glass-measuring-cup',
      category: 'bakeware',
      image: '/images/glass-measuring-cup.png',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
    {
      name: 'Rustic Ceramic Bakers',
      slug: 'rustic-ceramic-bakers',
      category: 'bakeware',
      image: '/images/dress.png',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
    {
      name: 'Craft Sheet Pan',
      slug: 'craft-sheet-pan',
      category: 'bakeware',
      image: '/images/dress.png',
      price: 500,
      countInStock: 10,
      brand: 'Gelo',
      rating: 4.5,
      numReviews: 10,
      description: 'Used for removing bones from meat',
    },
  ],
};
export default data;
